# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Full Stack Toronto 2018 <typeout>"
email: "comms@fsto.co"
description: "FSTO is conference for web developers focusing on senior and quality content."
baseurl: ""
url: "https://fsto.co"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-48190009-2"
googleAnalyticsSiteUrl: "fsto.co"
siteVerification: "2dVIu83aF5CgxgbO2Oj8UDYVxOcp3T9UK5kLDqX_63s"

# Organizer Info
organizerName: "Full Stack Toronto"
organizerAlternateName: "FSTO"
organizerDescription: "Full Stack Toronto is a non-profit organization that grows web developers with high quality and practical content."
organizerEmail: "comms@fsto.co"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://fsto.co/"

# Head
metaKeywords: "event, devfest, programming, developers, web development, development, full stack toronto, full stack, toronto, ontario, canada, web development conference, conference, training, event, web event, front-end, back-end, leadership, management"
twitterAccount: "@fstoco"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://www.papercall.io/fstoco18"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Full Stack Toronto 2018"
eventDate: "November 15 &amp; 16, 2018"
typeoutTextValues: '""'
typeoutFallback: ""
heroButtons:
 - {link: "https://www.papercall.io/fstoco18", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "The Full Stack Toronto Experience"
aboutBlock:
 - {title: "Diversity & Inclusion", image: "conference.jpg", text: "#fstoco is organized by a diverse group of individuals, and seeks to have a diverse line-up of speakers. We make sure that our event is a safe space for learning including gender non-binary washrooms and an enforced code of conduct. We also take great pride in attracting attendees from all around the world. Toronto is diverse and so should it’s leading tech event!" }
 - {title: "Curated Content", image: "workshop.jpg", text: "Our planning process starts with great quality content, we carefully select topics that you can go right back to work and start integrating into your existing stack. Those topics are laid out in the schedule so you get exposed to more than just your specialization and stack, then find amazing speakers to talk in those spots. This is a lot different than the traditional CFP process." }
 - {title: "Networking", image: "workshop.jpg", text: "We design our networking around breaking down barriers. We offer you a space on your name tag to put your passion so someone else can make that first intro, we’ve put games, lego, and other icebreakers around the venue so you can come together over a common task to feel less interrogated and a mix of designers and developers at the event spurs amazing conversations!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from around the world"}
 - {count: "2", specialCharacter: "", info: "days", detail: "of pure learning"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "across all of tech"}
 - {count: "40", specialCharacter: "%", info: "representation", detail: "by typically underreresented demos"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Highlighted speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Telus Digital"
eventLocationLink: "https://labs.telus.com/"
eventStreetAddress: "25 York St"
eventAddressLocality: "Toronto"
eventAddressLocalityRegion: "Ontario"
eventPostalCode: "M5J 2V5"
eventAddressCountry: "Canada"
eventStartTime: "2018-11-15T9:00"
eventDoorTime: "08:30"
eventEndTime: "2018-11-16T20:00"
eventPlaceCoordinates: "43.643452, -79.380987"
mapCenterCoordinates: "43.643452, -79.380987"
mapMobileCenterCoordinates: "43.643452, -79.380987"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "TELUS Digital"
venueFeatures: ["4 huge screens", "clear audio system", "Located directly at Union station!"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "fstoco"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of July. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, lunch and party. Accommodation is NOT included in the ticket price. We do not provide visas"
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "CAD"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["", "", ""]
  validFrom: "2018-04-25T10:00"
  validThrough: "2018-11-01T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "CAD"
  ticketsNumber: "150"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["", "", ""]
  validFrom: "2018-08-01T00:00"
  validThrough: "2018-11-13T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "CAD"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["", "", ""]
  validFrom: "2018-04-25T10:00"
  validThrough: "2018-11-14T23:59"
  soldOut: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=fullstackto", icon: "twitter"}
 - {link: "https://facebook.com/fullstackto", icon: "facebook"}
footerBlocks:
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "fstoco"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: ""

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "43.643452, -79.380987"
logisticsMapMobileCenterCoordinates: "43.643452, -79.380987"
logisticsMapAutoDirections: true

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Toronto"
directionDetailsCards:
 - {title: "From the Airport", information: 'Toronto Pearson International Airport (YYZ) is located 25 minutes from downtown via the UP Express ($9CAD)'}
 - {title: "Public Transit", information: 'Transit is the local app of choice for information on the TTC system, GO Trasit system, and BikeShare locations'}
 - {title: "Hotels", information: 'Toronto has lots of great hotels and a few hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "TBA"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
